### ISSUE TITLE
채팅에 입력할 수 있는 문자열의 길이는 얼마나 될까요?

### ISSUE THREAD

**Issue by soulchicken** [TeamATM/toonchat-client#10]
DB에 넣을 문자열의 길이가 얼마나 될 지,
AI가 받아줄 수 있는 문자열의 길이가 얼마나 될 지 안다면
엄청 엄청 좋을 것 같습니다. 우리 함께 찾아보아요.

**Comment by MustSave** [comment]
토큰을 기준으로 4096까지 받아들일 수 있을 것 같은데 긴 문장으로 학습되지 않았고, 이전 대화 내역이나 추가 정보 등이 같이 입력되어야 하기에 공백 포함 100자 이내가 좋을 것 같습니다.

**Comment by soulchicken** [comment]
그렇다면 현재 임시로 해놓은 maxLength값이 마침 100으로 이대로 두겠습니다.
백엔드나 AI 서버 측에서도 너무 많은 글자가 들어오는 것을 확인해서 막아주세요~🔥🔥
